### ISSUE TITLE
Add installation of pvlib for Google Colab

### ISSUE THREAD

**Issue by AdamRJensen** [PV-Tutorials/2024_Modeling_Webinar#3]
Currently the notebook isn't runnable in Google Collab because pvlib isn't installed. This can be achieved by adding the line `!pip install pvlib`

<img width="522" alt="image" src="https://github.com/PV-Tutorials/2024_Modeling_Webinar/assets/39184289/94e855a6-30c9-4379-812f-d8275de86e81">

**Comment by kandersolar** [comment]
Launch buttons are now removed
