### ISSUE TITLE
Data not accesible in Google Collab or MyBinder

### ISSUE THREAD

**Issue by AdamRJensen** [PV-Tutorials/2024_Modeling_Webinar#4]
<img width="503" alt="image" src="https://github.com/PV-Tutorials/2024_Modeling_Webinar/assets/39184289/2d127125-2f47-4748-819a-0bd046ad356c">

**Comment by AdamRJensen** [comment]
If the notebooks cannot be run in these active environments, then I think the button should be removed as not to mislead users.

**Comment by kandersolar** [comment]
Right, I am not planning for this tutorial to be readily usable in a cloud host.  It is probably possible for the notebooks to download the needed data as the first step, but it would take a while.  And anyway this notebook is not going to be presented such that the audience is intended to be following along with their own copy of the notebook.

I was going to do a bit of final cleanup today, including removing the "launch" buttons :)

**Comment by kandersolar** [comment]
Launch buttons are now removed
