### ISSUE TITLE
Mybinder issue with matplotlib

### ISSUE THREAD

**Issue by AdamRJensen** [PV-Tutorials/2024_Modeling_Webinar#5]
When loading the notebook with MyBinder there is an issue with finding matplotlib but not pvlib.

<img width="497" alt="image" src="https://github.com/PV-Tutorials/2024_Modeling_Webinar/assets/39184289/f85c4378-2e45-4901-99ba-155c0a4ba64c">

**Comment by kandersolar** [comment]
Launch buttons are now removed
