### ISSUE TITLE
Section on inverter outage

### ISSUE THREAD

**Issue by AdamRJensen** [PV-Tutorials/2024_Modeling_Webinar#7]
I'd love to see an additional section on figuring out the inverter outage stuff. This doesn't necessarily have to be in the presentation, but it could be left as a teaser for people to come back to explore if they're interested (I actually think that could be a great idea). Leave them wanting more!

<img width="521" alt="image" src="https://github.com/PV-Tutorials/2024_Modeling_Webinar/assets/39184289/01c7d9c0-6f21-4fd3-94ba-ac50491353d1">

**Comment by kandersolar** [comment]
There likely will not be time to say much about the inverter outage during the webinar, but I've added a brief list of ideas at the end of the notebook to prompt self-exploration :)
